apiVersion: addons.sigs.k8s.io/v1alpha1
kind: config-management
metadata:
  name: config-management
  namespace: config-management-system
spec:
  enableHierarchicalResourceQuota: true
  git:
    secretType: ssh
    syncRepo: git@github.com:haddon426/nomos-acme-corp.git
    syncBranch: master
    policyDir: nomos-root

